# Generated by Django 3.1.2 on 2020-10-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cateogry',
            new_name='category',
        ),
    ]
