# Generated by Django 3.1.2 on 2020-10-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201016_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_bids',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
