# Generated by Django 3.1.2 on 2020-10-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='owner',
        ),
    ]
